services:
  n8n:
    user: root
    build:
      context: .
      dockerfile: Dockerfile.n8n
    container_name: n8n
    network_mode: host
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_HOST=n8n.ivanildobarauna.dev
      - WEBHOOK_TUNNEL_URL=https://n8n.ivanildobarauna.dev
      - WEBHOOK_URL=https://n8n.ivanildobarauna.dev/
      - GENERIC_TIMEZONE=UTC
      - N8N_PORT=5678
      - N8N_REDIS_HOST=redis
      - N8N_REDIS_PORT=6379
      - N8N_REDIS_DB=0
      - N8N_REDIS_PASSWORD=${REDIS_PASSWORD}
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_JWT_SECRET}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      # Configurações do PostgreSQL
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: n8n_data
        target: /home/node/.n8n
        volume:
          nocopy: true
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    tty: true
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--requirepass", "${REDIS_PASSWORD}",
      "--protected-mode", "yes",
      "--maxmemory", "512mb",
      "--maxmemory-policy", "allkeys-lru"
    ]
    volumes:
      - redis_data:/data
    networks:
      - app_network

networks:
  app_network:
    name: app_network
    driver: bridge

volumes:
  n8n_data:
    external: true
  postgres_data:
    external: true
  redis_data:
    external: true
  ollama_data:
    external: true