FROM n8nio/n8n

USER root

RUN apk update && \
    apk add docker-cli curl

# Copia os arquivos de tracing para dentro do container
COPY ./n8n/data /tracer

# Instala o dd-trace localmente no diretório do tracer
# RUN cd /tracer && npm install

USER node
