services:
  n8n:
    user: root
    build:
      context: .
      dockerfile: Dockerfile.n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=n8nadm
      - N8N_HOST=n8n.ivanildobarauna.dev
      - WEBHOOK_TUNNEL_URL=https://n8n.ivanildobarauna.dev
      - WEBHOOK_URL=https://n8n.ivanildobarauna.dev/
      - GENERIC_TIMEZONE=UTC
      - N8N_PORT=5678
    volumes:
      - n8n_data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    expose:
      - "11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    tty: true

volumes:
  n8n_data:
  ollama_data:
