services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    expose:
      - "5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=suasenha
      - N8N_HOST=n8n.ivanildobarauna.dev
      - WEBHOOK_TUNNEL_URL=https://n8n.ivanildobarauna.dev
      - WEBHOOK_URL=https://n8n.ivanildobarauna.dev/
      - N8N_PORT=5678
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    expose:
      - "11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    tty: true  # importante para o ollama funcionar bem

volumes:
  n8n_data:
  ollama_data:
